config/routes.rb
Rails.application.routes.draw do
  resources :ports
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "categories#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :ports, dependent: :destroy
end

app/models/port.rb
class Port < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
    @ports = Port.all
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/ports_controller.rb
class PortsController < ApplicationController
  before_action :set_port, only: %i[ show edit update destroy ]

  # GET /ports or /ports.json
  def index
    @ports = Port.all
  end

  # GET /ports/1 or /ports/1.json
  def show
  end

  # GET /ports/new
  def new
    @port = Port.new
  end

  # GET /ports/1/edit
  def edit
  end

  # POST /ports or /ports.json
  def create
    @port = Port.new(port_params)

    respond_to do |format|
      if @port.save
        format.html { redirect_to port_url(@port), notice: "Port was successfully created." }
        format.json { render :show, status: :created, location: @port }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @port.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ports/1 or /ports/1.json
  def update
    respond_to do |format|
      if @port.update(port_params)
        format.html { redirect_to port_url(@port), notice: "Port was successfully updated." }
        format.json { render :show, status: :ok, location: @port }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @port.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ports/1 or /ports/1.json
  def destroy
    @port.destroy

    respond_to do |format|
      format.html { redirect_to ports_url, notice: "Port was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_port
      @port = Port.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def port_params
      params.require(:port).permit(:name, :description, :summary, :url, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/ports_helper.rb
module PortsHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>" class="category">
  <h1><%= link_to category.name, category %></h1>
  <p><%= category.ports.count %> ports</p>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<%= render partial: "shared/header" %>
<main>
  <% @categories.each do |category| %>
    <%= render category %>
  <% end %>
</main>
<%= render partial: "shared/footer" %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<%= render partial: "shared/header" %>
<main>
  <%= render @category %>
  <div class="options">
    <%= link_to "Edit", edit_category_path(@category) %>
    <%= link_to "Delete", @category, method: :delete, class: "button" %>
  </div>
  <% @ports.each do |port| %>
    <article>
      <h2><%= link_to port.name, port %></h2>
      <% if port.summary %>
        <%= tag.p port.summary, class: "summary" %>
      <% end %>
      <% if port.description %>
        <%= tag.p port.description, class: "description" %>
      <% end %>
      <% if port.url %>
        <%= link_to port.url, "#{ port.url }" %>
      <% end %>
    </article>
  </main>
<% end %>
<%= render partial: "shared/footer" %>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OpenBSD packages - Openports.no</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ports/_form.html.erb
<%= form_with(model: port) do |form| %>
  <% if port.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(port.errors.count, "error") %> prohibited this port from being saved:</h2>

      <ul>
        <% port.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :summary, style: "display: block" %>
    <%= form.text_field :summary %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.number_field :category_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ports/_port.html.erb
<div id="<%= dom_id port %>">
  <p>
    <strong>Name:</strong>
    <%= port.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= port.description %>
  </p>

  <p>
    <strong>Summary:</strong>
    <%= port.summary %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= port.url %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= port.category_id %>
  </p>

</div>

app/views/ports/edit.html.erb
<h1>Editing port</h1>

<%= render "form", port: @port %>

<br>

<div>
  <%= link_to "Show this port", @port %> |
  <%= link_to "Back to ports", ports_path %>
</div>

app/views/ports/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Ports</h1>

<div id="ports">
  <% @ports.each do |port| %>
    <%= render port %>
    <p>
      <%= link_to "Show this port", port %>
    </p>
  <% end %>
</div>

<%= link_to "New port", new_port_path %>

app/views/ports/new.html.erb
<h1>New port</h1>

<%= render "form", port: @port %>

<br>

<div>
  <%= link_to "Back to ports", ports_path %>
</div>

app/views/ports/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @port %>

<div>
  <%= link_to "Edit this port", edit_port_path(@port) %> |
  <%= link_to "Back to ports", ports_path %>

  <%= button_to "Destroy this port", @port, method: :delete %>
</div>

app/views/shared/_footer.html.erb
<footer>
  <p class="stats">13,242 ports spread among 723 users</p>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="logo">Openports.org</div>
  <input type="text/css" placeholder="Search by name...">
  <div class="buttons">
    <%= link_to "New port", new_port_path %>
    <a href="#">Login</a>
  </div>
</header>